version: '3'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql://admin:sama1234weera@rds-endpoint/applicationdb
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sama1234weera
      MYSQL_DATABASE: applicationdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234

  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"